// Random recipe data that is added to Firestore
// After you've signed into RecipeAI, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  recipeNames: [
    "Classic Spaghetti Carbonara",
    "Chicken Tikka Masala",
    "Beef Stir Fry",
    "Mediterranean Quinoa Bowl",
    "Creamy Mushroom Risotto",
    "Thai Green Curry",
    "Homemade Pizza Margherita",
    "Chocolate Chip Cookies",
    "Grilled Salmon with Herbs",
    "Vegetable Lasagna",
    "Chicken Noodle Soup",
    "Beef Tacos",
    "Caesar Salad",
    "Pancakes with Maple Syrup",
    "Fish and Chips",
    "Chicken Parmesan",
    "Vegetable Stir Fry",
    "Chocolate Brownies",
    "Grilled Chicken Breast",
    "Pasta Primavera",
    "Beef Burger",
    "Greek Salad",
    "Apple Pie",
    "Chicken Fajitas",
    "Vegetable Soup",
    "Chocolate Cake",
    "Grilled Vegetables",
    "Chicken Fried Rice",
    "Beef Stew",
    "Fruit Smoothie",
    "Chicken Wings",
    "Vegetable Curry",
    "Chocolate Mousse",
    "Grilled Fish",
    "Pasta Salad",
    "Beef Sandwich",
    "Vegetable Pasta",
    "Chocolate Pudding",
    "Chicken Salad",
    "Vegetable Soup",
    "Beef Noodles",
    "Fruit Salad",
    "Chicken Wrap",
    "Vegetable Pizza",
    "Chocolate Ice Cream",
    "Grilled Steak",
    "Pasta Carbonara",
    "Beef Curry",
    "Vegetable Stir Fry",
    "Chocolate Fondue",
    "Chicken Soup"
  ],
  cuisineTypes: [
    "Italian",
    "Chinese",
    "Japanese",
    "Mexican",
    "Indian",
    "Mediterranean",
    "American",
    "French",
    "Thai",
    "Korean",
    "Vietnamese",
    "Greek",
    "Spanish",
    "German",
    "Middle Eastern"
  ],
  difficultyLevels: [
    "Easy",
    "Medium",
    "Hard"
  ],
  cookingTimes: [
    "< 15 min",
    "15-30 min",
    "30-60 min",
    "60+ min"
  ],
  dietaryRestrictions: [
    "Vegetarian",
    "Vegan",
    "Gluten-Free",
    "Dairy-Free",
    "Nut-Free",
    "Low-Carb",
    "Keto",
    "Paleo",
    "Halal",
    "Kosher"
  ],
  ingredients: [
    // Proteins & Meats
    "bacon",
    "beef broth",
    "beef jerky",
    "beef tenderloin",
    "black beans",
    "canned tuna",
    "chicken broth",
    "chicken breast",
    "chicken drumsticks",
    "chicken thighs",
    "chicken wings",
    "chickpeas",
    "chorizo",
    "cod",
    "crab",
    "duck breast",
    "eggs",
    "ground beef",
    "ground chicken",
    "ground pork",
    "ground turkey",
    "ham",
    "kidney beans",
    "lamb chops",
    "lobster",
    "pinto beans",
    "pork chops",
    "pork tenderloin",
    "prosciutto",
    "salmon fillet",
    "sausage",
    "scallops",
    "shrimp",
    "tempeh",
    "tofu",
    "turkey",
    "white beans",
    
    // Vegetables
    "artichoke",
    "arugula",
    "asparagus",
    "beets",
    "bell peppers",
    "broccoli",
    "brussels sprouts",
    "cabbage",
    "carrots",
    "cauliflower",
    "celery",
    "corn",
    "cucumber",
    "eggplant",
    "fennel",
    "green beans",
    "jalapeño",
    "kale",
    "leeks",
    "lettuce",
    "mushrooms",
    "okra",
    "onion",
    "peas",
    "poblano pepper",
    "potatoes",
    "pumpkin",
    "radish",
    "red onion",
    "scallions",
    "serrano pepper",
    "shallots",
    "spinach",
    "squash",
    "sweet potato",
    "tomatoes",
    "turnip",
    "zucchini",
    
    // Fruits
    "apple",
    "apricot",
    "avocado",
    "banana",
    "blackberries",
    "blueberries",
    "cantaloupe",
    "cherries",
    "coconut",
    "cranberries",
    "dates",
    "figs",
    "grapes",
    "kiwi",
    "lemon",
    "lime",
    "mango",
    "orange",
    "papaya",
    "peach",
    "pear",
    "pineapple",
    "plum",
    "pomegranate",
    "raspberries",
    "strawberries",
    "watermelon",
    
    // Herbs & Aromatics
    "basil",
    "bay leaves",
    "chives",
    "cilantro",
    "curry leaves",
    "dill",
    "garlic",
    "ginger",
    "lemongrass",
    "mint",
    "oregano",
    "parsley",
    "rosemary",
    "sage",
    "tarragon",
    "thyme",
    
    // Spices & Seasonings
    "allspice",
    "cardamom",
    "cayenne pepper",
    "chili powder",
    "cinnamon",
    "cloves",
    "coriander",
    "cumin",
    "curry powder",
    "dried basil",
    "dried oregano",
    "fennel seeds",
    "garlic powder",
    "garam masala",
    "italian seasoning",
    "nutmeg",
    "onion powder",
    "paprika",
    "red pepper flakes",
    "salt",
    "smoked paprika",
    "star anise",
    "turmeric",
    "vanilla extract",
    
    // Grains & Starches
    "barley",
    "bread",
    "breadcrumbs",
    "bulgur",
    "couscous",
    "farro",
    "naan",
    "noodles",
    "oats",
    "panko breadcrumbs",
    "pasta",
    "pita bread",
    "polenta",
    "quinoa",
    "ramen",
    "rice",
    "soba noodles",
    "tortillas",
    "udon",
    
    // Dairy & Alternatives
    "almond milk",
    "butter",
    "buttermilk",
    "cheddar cheese",
    "coconut milk",
    "cream",
    "cream cheese",
    "feta cheese",
    "goat cheese",
    "heavy cream",
    "milk",
    "mozzarella",
    "oat milk",
    "parmesan cheese",
    "sour cream",
    "soy milk",
    "vegetable broth",
    "yogurt",
    
    // Oils & Condiments
    "BBQ sauce",
    "canola oil",
    "coconut oil",
    "fish sauce",
    "hoisin sauce",
    "hot sauce",
    "ketchup",
    "mayonnaise",
    "olive oil",
    "peanut butter",
    "pesto",
    "sesame oil",
    "sriracha",
    "tahini",
    "vegetable oil",
    "worcestershire sauce",
    
    // Baking & Sweets
    "agave nectar",
    "baking powder",
    "baking soda",
    "brown sugar",
    "chocolate chips",
    "cocoa powder",
    "cornstarch",
    "dark chocolate",
    "flour",
    "honey",
    "maple syrup",
    "molasses",
    "powdered sugar",
    "sugar",
    "white chocolate",
    "yeast",
    
    // Canned/Jarred Items
    "canned corn",
    "capers",
    "coconut cream",
    "diced tomatoes",
    "olives",
    "pickles",
    "sun-dried tomatoes",
    "tomato paste",
    "tomato sauce",
    
    // Vinegars & Acids
    "apple cider vinegar",
    "balsamic vinegar",
    "lemon juice",
    "lime juice",
    "red wine vinegar",
    "vinegar",
    "white wine vinegar",
    
    // Beverages & Alcohol
    "red wine",
    "white wine",
    
    // Nuts & Seeds
    "almonds",
    "cashews",
    "chia seeds",
    "flax seeds",
    "hazelnuts",
    "macadamia nuts",
    "peanuts",
    "pecans",
    "pine nuts",
    "pistachios",
    "pumpkin seeds",
    "sesame seeds",
    "sunflower seeds",
    "walnuts",
    
    // Dried Fruits
    "dried apricots",
    "dried cranberries",
    "dried figs",
    "raisins",
    
    // Specialty Items
    "miso paste",
    "seaweed",
    "truffle oil",
    
    // Frozen Items
    "frozen berries",
    "frozen corn",
    "frozen peas",
    "frozen spinach",
    
    // Additional Common Items
    "anchovies",
    "artichoke hearts",
    "bamboo shoots",
    "bean sprouts",
    "bok choy",
    "canned beans",
    "canned chickpeas",
    "canned tomatoes",
    "cheese",
    "chicken stock",
    "coconut oil",
    "corn kernels",
    "cream of coconut",
    "dried mushrooms",
    "edamame",
    "fresh herbs",
    "garbanzo beans",
    "green onions",
    "ground lamb",
    "ground veal",
    "halibut",
    "hearts of palm",
    "jicama",
    "kalamata olives",
    "lentils",
    "mahi mahi",
    "marshmallows",
    "mascarpone",
    "miso",
    "mushroom broth",
    "nutritional yeast",
    "oyster sauce",
    "pancetta",
    "pepper",
    "poblano peppers",
    "portobello mushrooms",
    "prosciutto",
    "red bell pepper",
    "red pepper",
    "ricotta cheese",
    "roasted red peppers",
    "saffron",
    "sea salt",
    "shiitake mushrooms",
    "snow peas",
    "sugar snap peas",
    "sumac",
    "swiss chard",
    "tamarind",
    "truffle",
    "vegetable stock",
    "water chestnuts",
    "white beans",
    "yellow bell pepper",
    "zucchini squash"
  ],
  recipeReviews: [
    { text: "This recipe was absolutely delicious! Easy to follow and the flavors were amazing.", rating: 5 },
    { text: "Perfect recipe, turned out exactly as expected. Highly recommend!", rating: 5 },
    { text: "The instructions were clear and the dish was fantastic.", rating: 5 },
    { text: "Great recipe! My family loved it and asked for seconds.", rating: 5 },
    { text: "Simple ingredients but incredible taste. Will make again!", rating: 5 },
    { text: "This recipe exceeded my expectations. Delicious and satisfying.", rating: 5 },
    { text: "Easy to make and the results were restaurant-quality.", rating: 5 },
    { text: "Perfect for a weeknight dinner. Quick and tasty!", rating: 5 },
    { text: "Good recipe, turned out well. Would make again.", rating: 4 },
    { text: "Nice flavors, though I made a few adjustments to suit my taste.", rating: 4 },
    { text: "Decent recipe, easy to follow. Good for beginners.", rating: 4 },
    { text: "Tasty dish, though it took longer than expected to prepare.", rating: 4 },
    { text: "The recipe was okay, but not quite what I was looking for.", rating: 3 },
    { text: "Average recipe. Nothing special but edible.", rating: 3 },
    { text: "The instructions were a bit unclear in places.", rating: 3 },
    { text: "The dish was bland and needed more seasoning.", rating: 2 },
    { text: "Not impressed with this recipe. Too much work for mediocre results.", rating: 2 },
    { text: "The recipe didn't turn out as described. Disappointing.", rating: 2 },
    { text: "Terrible recipe. Waste of ingredients and time.", rating: 1 },
    { text: "This was inedible. Would not recommend to anyone.", rating: 1 },
    { text: "The worst recipe I've ever tried. Complete failure.", rating: 1 },
    { text: "Absolutely amazing! This recipe is now a family favorite.", rating: 5 },
    { text: "Incredible flavors and so easy to make. Love it!", rating: 5 },
    { text: "This recipe is a game-changer. Perfect every time!", rating: 5 },
    { text: "Outstanding recipe! Restaurant quality at home.", rating: 5 },
    { text: "This recipe never fails to impress. Simply perfect!", rating: 5 },
    { text: "Excellent recipe with clear instructions. Delicious results!", rating: 5 },
    { text: "Fantastic recipe! Will definitely be making this again.", rating: 5 },
    { text: "Perfect recipe for special occasions. Always a hit!", rating: 5 },
    { text: "Good recipe overall, though I'd add a bit more spice next time.", rating: 4 },
    { text: "Solid recipe. Easy to follow and tastes great.", rating: 4 },
    { text: "Nice recipe, though it could use more detailed timing.", rating: 4 },
    { text: "Decent recipe. Good for a quick meal.", rating: 4 },
    { text: "The recipe was fine, but not exceptional.", rating: 3 },
    { text: "Average recipe. Nothing wrong with it, but nothing special either.", rating: 3 },
    { text: "The recipe was okay, but I've had better versions.", rating: 3 },
    { text: "Disappointing recipe. The flavors didn't come together well.", rating: 2 },
    { text: "Not worth the effort. The result was underwhelming.", rating: 2 },
    { text: "The recipe had potential but fell short in execution.", rating: 2 },
    { text: "This recipe was a complete disaster. Avoid at all costs.", rating: 1 },
    { text: "Horrible recipe. Ruined my dinner plans.", rating: 1 },
    { text: "This recipe is terrible. Don't waste your time.", rating: 1 }
  ]
};
