// Random recipe data that is added to Firestore
// After you've signed into RecipeAI, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  recipeNames: [
    "Classic Spaghetti Carbonara",
    "Chicken Tikka Masala",
    "Beef Stir Fry",
    "Mediterranean Quinoa Bowl",
    "Creamy Mushroom Risotto",
    "Thai Green Curry",
    "Homemade Pizza Margherita",
    "Chocolate Chip Cookies",
    "Grilled Salmon with Herbs",
    "Vegetable Lasagna",
    "Chicken Noodle Soup",
    "Beef Tacos",
    "Caesar Salad",
    "Pancakes with Maple Syrup",
    "Fish and Chips",
    "Chicken Parmesan",
    "Vegetable Stir Fry",
    "Chocolate Brownies",
    "Grilled Chicken Breast",
    "Pasta Primavera",
    "Beef Burger",
    "Greek Salad",
    "Apple Pie",
    "Chicken Fajitas",
    "Vegetable Soup",
    "Chocolate Cake",
    "Grilled Vegetables",
    "Chicken Fried Rice",
    "Beef Stew",
    "Fruit Smoothie",
    "Chicken Wings",
    "Vegetable Curry",
    "Chocolate Mousse",
    "Grilled Fish",
    "Pasta Salad",
    "Beef Sandwich",
    "Vegetable Pasta",
    "Chocolate Pudding",
    "Chicken Salad",
    "Vegetable Soup",
    "Beef Noodles",
    "Fruit Salad",
    "Chicken Wrap",
    "Vegetable Pizza",
    "Chocolate Ice Cream",
    "Grilled Steak",
    "Pasta Carbonara",
    "Beef Curry",
    "Vegetable Stir Fry",
    "Chocolate Fondue",
    "Chicken Soup"
  ],
  cuisineTypes: [
    "Italian",
    "Chinese",
    "Japanese",
    "Mexican",
    "Indian",
    "Mediterranean",
    "American",
    "French",
    "Thai",
    "Korean",
    "Vietnamese",
    "Greek",
    "Spanish",
    "German",
    "Middle Eastern"
  ],
  difficultyLevels: [
    "Easy",
    "Medium",
    "Hard"
  ],
  cookingTimes: [
    "< 15 min",
    "15-30 min",
    "30-60 min",
    "60+ min"
  ],
  dietaryRestrictions: [
    "Vegetarian",
    "Vegan",
    "Gluten-Free",
    "Dairy-Free",
    "Nut-Free",
    "Low-Carb",
    "Keto",
    "Paleo",
    "Halal",
    "Kosher"
  ],
  ingredients: [
    "chicken breast",
    "ground beef",
    "salmon fillet",
    "eggs",
    "milk",
    "butter",
    "olive oil",
    "garlic",
    "onion",
    "tomatoes",
    "bell peppers",
    "mushrooms",
    "spinach",
    "broccoli",
    "carrots",
    "potatoes",
    "rice",
    "pasta",
    "bread",
    "cheese",
    "flour",
    "sugar",
    "salt",
    "pepper",
    "basil",
    "oregano",
    "thyme",
    "parsley",
    "cilantro",
    "ginger",
    "lemon",
    "lime",
    "avocado",
    "cucumber",
    "lettuce",
    "cabbage",
    "zucchini",
    "eggplant",
    "sweet potato",
    "corn",
    "beans",
    "lentils",
    "quinoa",
    "oats",
    "almonds",
    "walnuts",
    "honey",
    "maple syrup",
    "vanilla extract",
    "cinnamon",
    "nutmeg",
    "paprika",
    "cumin",
    "turmeric",
    "soy sauce",
    "vinegar",
    "mustard",
    "mayonnaise",
    "yogurt",
    "cream",
    "coconut milk",
    "chicken broth",
    "vegetable broth",
    "wine",
    "baking powder",
    "baking soda",
    "chocolate chips",
    "nuts",
    "berries",
    "banana",
    "apple",
    "orange",
    "lemon juice",
    "lime juice"
  ],
  recipeReviews: [
    { text: "This recipe was absolutely delicious! Easy to follow and the flavors were amazing.", rating: 5 },
    { text: "Perfect recipe, turned out exactly as expected. Highly recommend!", rating: 5 },
    { text: "The instructions were clear and the dish was fantastic.", rating: 5 },
    { text: "Great recipe! My family loved it and asked for seconds.", rating: 5 },
    { text: "Simple ingredients but incredible taste. Will make again!", rating: 5 },
    { text: "This recipe exceeded my expectations. Delicious and satisfying.", rating: 5 },
    { text: "Easy to make and the results were restaurant-quality.", rating: 5 },
    { text: "Perfect for a weeknight dinner. Quick and tasty!", rating: 5 },
    { text: "Good recipe, turned out well. Would make again.", rating: 4 },
    { text: "Nice flavors, though I made a few adjustments to suit my taste.", rating: 4 },
    { text: "Decent recipe, easy to follow. Good for beginners.", rating: 4 },
    { text: "Tasty dish, though it took longer than expected to prepare.", rating: 4 },
    { text: "The recipe was okay, but not quite what I was looking for.", rating: 3 },
    { text: "Average recipe. Nothing special but edible.", rating: 3 },
    { text: "The instructions were a bit unclear in places.", rating: 3 },
    { text: "The dish was bland and needed more seasoning.", rating: 2 },
    { text: "Not impressed with this recipe. Too much work for mediocre results.", rating: 2 },
    { text: "The recipe didn't turn out as described. Disappointing.", rating: 2 },
    { text: "Terrible recipe. Waste of ingredients and time.", rating: 1 },
    { text: "This was inedible. Would not recommend to anyone.", rating: 1 },
    { text: "The worst recipe I've ever tried. Complete failure.", rating: 1 },
    { text: "Absolutely amazing! This recipe is now a family favorite.", rating: 5 },
    { text: "Incredible flavors and so easy to make. Love it!", rating: 5 },
    { text: "This recipe is a game-changer. Perfect every time!", rating: 5 },
    { text: "Outstanding recipe! Restaurant quality at home.", rating: 5 },
    { text: "This recipe never fails to impress. Simply perfect!", rating: 5 },
    { text: "Excellent recipe with clear instructions. Delicious results!", rating: 5 },
    { text: "Fantastic recipe! Will definitely be making this again.", rating: 5 },
    { text: "Perfect recipe for special occasions. Always a hit!", rating: 5 },
    { text: "Good recipe overall, though I'd add a bit more spice next time.", rating: 4 },
    { text: "Solid recipe. Easy to follow and tastes great.", rating: 4 },
    { text: "Nice recipe, though it could use more detailed timing.", rating: 4 },
    { text: "Decent recipe. Good for a quick meal.", rating: 4 },
    { text: "The recipe was fine, but not exceptional.", rating: 3 },
    { text: "Average recipe. Nothing wrong with it, but nothing special either.", rating: 3 },
    { text: "The recipe was okay, but I've had better versions.", rating: 3 },
    { text: "Disappointing recipe. The flavors didn't come together well.", rating: 2 },
    { text: "Not worth the effort. The result was underwhelming.", rating: 2 },
    { text: "The recipe had potential but fell short in execution.", rating: 2 },
    { text: "This recipe was a complete disaster. Avoid at all costs.", rating: 1 },
    { text: "Horrible recipe. Ruined my dinner plans.", rating: 1 },
    { text: "This recipe is terrible. Don't waste your time.", rating: 1 }
  ]
};
